### ISSUE TITLE
XeLaTeX doesn't work

### ISSUE THREAD

**Issue by dudongbi** [shuichiro-makigaki/docker-texlive-2017#1]
Hi, makigaki

`$ sudo docker run --rm -v $PWD:/workdir -w /workdir makisyu/texlive-2017 xelatex main.tex`
got
`xelatex: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory`

**Comment by ThomDietrich** [comment]
Seeing the same error.
@shuichiro-makigaki any advice?

**Comment by shuichiro-makigaki** [comment]
Really sorry for late reply, but thank you for letting me know the issue.

I will check this issue this week, and try to find a solution.

**Comment by dudongbi** [comment]
i solved this by

yum install fontconfig

guessing lost some fonts lib，now it works well

**Comment by ThomDietrich** [comment]
Works for me too. 

@shuichiro-makigaki thanks for this image! I've been looking for a fitting docker image for GitLab CI for hours like an idiot. Yours is now the only one with all tools and the latest versions to be able to build my project.

Could you please inform us when the above step is integrated in the build? Thanks

**Comment by shuichiro-makigaki** [comment]
@ThomDietrich The latest image is now available (after two retries...).

**Comment by ThomDietrich** [comment]
Confirmed working. Great job.
